### PR TITLE
Fix time configurations in the task listener

### LINKED ISSUE #8470: Incorrect behaviour in time configs in the task listener
### Description

The startTime and endTime configurations in the task:Listener do not behave as expected. For an example when a `startTime` is specified in the future, the first execution of the task is not getting delayed until that time.

### Steps to Reproduce

1. Run the following Ballerina program using `bal run`.

```ballerina
import ballerina/io;
import ballerina/task;
import ballerina/time;

time:Civil startTime = time:utcToCivil(time:utcAddSeconds(time:utcNow(), 5));
time:Civil endTime = time:utcToCivil(time:utcAddSeconds(time:utcNow(), 3));

listener task:Listener taskListener = new (
    trigger = {
        interval: 2,
        maxCount: 5,
        endTime
    }
);

service "job-1" on taskListener {
    private int i = 1;

    isolated function execute() returns error? {
        lock {
            io:println("Counter: ", self.i);
            self.i += 1;
        }
    }
}
```

2. Observe the Counter is printed immediatley not honouring the startTime

### Version

2.11.0

### Environment Details (with versions)

_No response_

### PR DESCRIPTION
**Pull request by Nuvindu**
## Purpose

Fixes: https://github.com/ballerina-platform/ballerina-library/issues/8470

This is to fix the incorrect behaviour of the task listener when applying `startTime`, `endTime` configurations.

## Checklist
- [ ] Linked to an issue
- [ ] Updated the changelog
- [ ] Added tests
- [ ] Updated the spec
- [ ] Checked native-image compatibility

### CODE REVIEW

File: native/src/main/java/io/ballerina/stdlib/task/listener/ListenerAction.java [hunk 1]
```diff
@@ -94,6 +95,21 @@ public static Object start(Environment environment, BObject listenerObj) {
         return null;
     }
 
+    private static Object civilToMillisIfNeeded(Environment env, Object value) throws Exception {
+        if (value == null) {
+            return null;
+        }
+        Object[] arguments = new Object[]{value};
+        StrandMetadata strandMetadata = new StrandMetadata(true,
```
Comment (TharmiganK) [inline native/src/main/java/io/ballerina/stdlib/task/listener/ListenerAction.java]: I think properties are not required here. This property bag is used to share context between strands and I do not think that is required in this scenario

```suggestion
        StrandMetadata strandMetadata = new StrandMetadata(true, null);
```

File: native/src/main/java/io/ballerina/stdlib/task/listener/ListenerAction.java [hunk 2]
```diff
@@ -94,6 +94,19 @@ public static Object start(Environment environment, BObject listenerObj) {
         return null;
     }
 
+    private static Object civilToMillisIfNeeded(Environment env, Object value) throws Exception {
+        if (value == null) {
+            return null;
+        }
+        Object[] arguments = new Object[]{value};
+        Object result = env.getRuntime().callFunction(ModuleUtils.getModule(), GET_TIME_IN_MILLISECONDS,
+                null, arguments);
```
Comment (TharmiganK) [inline native/src/main/java/io/ballerina/stdlib/task/listener/ListenerAction.java]: Since this function is isolated, it is stable to call it with a different strand as well. For that, I think we need to explicitly set the strand metadata with isIsolated set to true (IIRC the default value is false):
```suggestion
                new StrandMetadata(true, null), arguments);
```

Comment (Nuvindu) [reply native/src/main/java/io/ballerina/stdlib/task/listener/ListenerAction.java]: It was a mistake. Fixed in [b57a8ca](https://github.com/ballerina-platform/module-ballerina-task/pull/543/commits/b57a8ca04e184b16d686e3b15252e76ba9d1f068)

File: native/src/main/java/io/ballerina/stdlib/task/listener/ListenerAction.java (hunk 1 above)
Comment (Nuvindu) [reply native/src/main/java/io/ballerina/stdlib/task/listener/ListenerAction.java]: Fixed in [b57a8ca](https://github.com/ballerina-platform/module-ballerina-task/pull/543/commits/b57a8ca04e184b16d686e3b15252e76ba9d1f068)

**Review by TharmiganK — APPROVED** [review]
